### ISSUE TITLE
[Feature] Add textfile collector support 

### ISSUE THREAD

**Issue by RaymondMouthaan** [lukasmalkmus/rpi_exporter#2]
Hello Lucas,

Via @carlosedp I came across rpi-exporter to get the temperature of raspberry pi's. Exactly what I needed! Thanks for that!

Currently I am using carlosedp/docker-arm_exporter to deploy a container on each of my docker nodes to get cpu temperature from each (raspberry pi) node. This works as expected, but it reports the ip address of the container instead of the node where it is running. 
 
rpi_cpu_temperature_celsius{instance="**10.0.1.26**:9243",job="arm-exporter"}	55.843
rpi_cpu_temperature_celsius{instance="**10.0.1.27**:9243",job="arm-exporter"}	48.312
rpi_cpu_temperature_celsius{instance="**10.0.1.28**:9243",job="arm-exporter"}	56.382
rpi_cpu_temperature_celsius{instance="**10.0.1.29**:9243",job="arm-exporter"}	56.92
rpi_cpu_temperature_celsius{instance="**10.0.1.30**:9243",job="arm-exporter"}	57.996

Would it be possible to add the textfile-collector feature (or similar) like [node-exporter](https://github.com/prometheus/node_exporter#textfile-collector) to rpi_exporter, so that we can pass the hostname and node_id to rpi_exporter?

The way it works for node_exporter is:

docker compose file:
```
node-exporter:
    image: raymondmm/node-exporter
    environment:
      # pass the nodeid as a environment var
      - NODE_ID={{.Node.ID}}
    volumes:
      # pass the hostname of the host to container
      - /etc/hostname:/etc/nodename:ro
    command:
      # tell node_exporter where prom files can be found 
      - '--collector.textfile.directory=/etc/node-exporter/'
    ports:
      - 9100:9100
    networks:
      - monitoring-net
    deploy:
      mode: global
      # placement:
      #  constraints:
      #    # - node.role == manager
      #    - node.hostname == docker1
      restart_policy:
        condition: on-failure
```

docker-entrypoint.sh
```
#!/bin/sh -e

NODE_NAME=$(cat /etc/nodename)
echo "node_meta{node_id=\"$NODE_ID\", container_label_com_docker_swarm_node_id=\"$NODE_ID\", node_name=\"$NODE_NAME\"} 1" > /etc/node-exporter/node-meta.prom

set -- /bin/node_exporter "$@"

exec "$@"
```

The above script creates a file node-meta.prom:
```
cat /etc/node-exporter/node-meta.prom
node_meta{node_id="c6qrb488g71accirnhe1n7qqb", container_label_com_docker_swarm_node_id="c6qrb488g71accirnhe1n7qqb", node_name="docker1"} 1
```

This file gets read by node_exporter and makes it possible to query with Prometheus like this
```
sum(node_memory_MemAvailable * on(instance) group_left(node_id, node_name) node_meta) by (node_id, node_name)
{node_id="wrdvtftteo0uaekmdq4dxrn14",node_name="docker1"} 889450496
{node_id="moggm3uaq8tax9ptr1if89pi7",node_name="docker2"} 1404162048
{node_id="vkdfx99mm5u4xl2drqhnwtnsv",node_name="docker3"} 1406574592
```

Instead of:
```
sum(node_memory_MemAvailable) by (instance)
{instance="10.0.0.5:9100"} 889450496
{instance="10.0.0.13:9100"} 1404162048
{instance="10.0.0.15:9100"} 1406574592
```

Thanks in advanced,
Raymond
